spring:
 datasource:
   username:foodbox
   password:7748426foodbox
   url:jdbc:mysql://foodboxdb.cwd0bxolrszv.ap-south-1.rds.amazonaws.com:3306/foodbox
 jpa:
   show-sql=true
   properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
   hibernate.ddl-auto=update
cloud:
  aws:
    credentials:
        access-key:AKIAZYDKTJ7NWBAYR2XF
        secret-key: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
    region:
        static:ap-south-1
    stack:
        auto:false
application:
  bucket:
     name:foodboxstorage